// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using atm.api.data.DBContext;

#nullable disable

namespace atm.api.web.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("atm.api.domain.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PIN")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Card");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 600.00m,
                            CardNumber = "1234567890123456",
                            Enabled = true,
                            PIN = "1234"
                        },
                        new
                        {
                            Id = 2,
                            Balance = 600.00m,
                            CardNumber = "9876543210987654",
                            Enabled = true,
                            PIN = "4321"
                        },
                        new
                        {
                            Id = 3,
                            Balance = 1000.00m,
                            CardNumber = "1111222233334444",
                            Enabled = true,
                            PIN = "5678"
                        },
                        new
                        {
                            Id = 4,
                            Balance = 150.00m,
                            CardNumber = "5555666677778888",
                            Enabled = true,
                            PIN = "8765"
                        },
                        new
                        {
                            Id = 5,
                            Balance = 650.00m,
                            CardNumber = "9999000011112222",
                            Enabled = true,
                            PIN = "9876"
                        });
                });

            modelBuilder.Entity("atm.api.domain.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OperationDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OperationTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("OperationTypeId");

                    b.ToTable("Operations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 0m,
                            CardId = 1,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 51, 510, DateTimeKind.Local).AddTicks(9204),
                            OperationTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = -100m,
                            CardId = 1,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 52, 510, DateTimeKind.Local).AddTicks(9212),
                            OperationTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Amount = 1400m,
                            CardId = 1,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 53, 510, DateTimeKind.Local).AddTicks(9214),
                            OperationTypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            Amount = -50m,
                            CardId = 1,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 54, 510, DateTimeKind.Local).AddTicks(9215),
                            OperationTypeId = 2
                        },
                        new
                        {
                            Id = 5,
                            Amount = 0m,
                            CardId = 1,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 55, 510, DateTimeKind.Local).AddTicks(9216),
                            OperationTypeId = 1
                        },
                        new
                        {
                            Id = 6,
                            Amount = 1350m,
                            CardId = 1,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 56, 510, DateTimeKind.Local).AddTicks(9218),
                            OperationTypeId = 3
                        },
                        new
                        {
                            Id = 7,
                            Amount = -300m,
                            CardId = 1,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 57, 510, DateTimeKind.Local).AddTicks(9220),
                            OperationTypeId = 2
                        },
                        new
                        {
                            Id = 8,
                            Amount = 0m,
                            CardId = 1,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 58, 510, DateTimeKind.Local).AddTicks(9221),
                            OperationTypeId = 1
                        },
                        new
                        {
                            Id = 9,
                            Amount = -200m,
                            CardId = 1,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 59, 510, DateTimeKind.Local).AddTicks(9222),
                            OperationTypeId = 2
                        },
                        new
                        {
                            Id = 10,
                            Amount = 850m,
                            CardId = 1,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 49, 0, 510, DateTimeKind.Local).AddTicks(9224),
                            OperationTypeId = 3
                        },
                        new
                        {
                            Id = 11,
                            Amount = -150m,
                            CardId = 1,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 49, 1, 510, DateTimeKind.Local).AddTicks(9225),
                            OperationTypeId = 2
                        },
                        new
                        {
                            Id = 12,
                            Amount = 0m,
                            CardId = 1,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 49, 2, 510, DateTimeKind.Local).AddTicks(9226),
                            OperationTypeId = 1
                        },
                        new
                        {
                            Id = 13,
                            Amount = 700m,
                            CardId = 1,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 49, 3, 510, DateTimeKind.Local).AddTicks(9228),
                            OperationTypeId = 3
                        },
                        new
                        {
                            Id = 14,
                            Amount = -100m,
                            CardId = 1,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 49, 4, 510, DateTimeKind.Local).AddTicks(9229),
                            OperationTypeId = 2
                        },
                        new
                        {
                            Id = 15,
                            Amount = 0m,
                            CardId = 1,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 49, 5, 510, DateTimeKind.Local).AddTicks(9230),
                            OperationTypeId = 1
                        },
                        new
                        {
                            Id = 16,
                            Amount = 0m,
                            CardId = 2,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 51, 510, DateTimeKind.Local).AddTicks(9231),
                            OperationTypeId = 1
                        },
                        new
                        {
                            Id = 17,
                            Amount = -100m,
                            CardId = 2,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 52, 510, DateTimeKind.Local).AddTicks(9233),
                            OperationTypeId = 2
                        },
                        new
                        {
                            Id = 18,
                            Amount = 1400m,
                            CardId = 2,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 53, 510, DateTimeKind.Local).AddTicks(9235),
                            OperationTypeId = 3
                        },
                        new
                        {
                            Id = 19,
                            Amount = -50m,
                            CardId = 2,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 54, 510, DateTimeKind.Local).AddTicks(9236),
                            OperationTypeId = 2
                        },
                        new
                        {
                            Id = 20,
                            Amount = 0m,
                            CardId = 2,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 55, 510, DateTimeKind.Local).AddTicks(9237),
                            OperationTypeId = 1
                        },
                        new
                        {
                            Id = 21,
                            Amount = 1350m,
                            CardId = 2,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 56, 510, DateTimeKind.Local).AddTicks(9238),
                            OperationTypeId = 3
                        },
                        new
                        {
                            Id = 22,
                            Amount = -300m,
                            CardId = 2,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 57, 510, DateTimeKind.Local).AddTicks(9240),
                            OperationTypeId = 2
                        },
                        new
                        {
                            Id = 23,
                            Amount = 0m,
                            CardId = 2,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 58, 510, DateTimeKind.Local).AddTicks(9241),
                            OperationTypeId = 1
                        },
                        new
                        {
                            Id = 24,
                            Amount = -200m,
                            CardId = 2,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 59, 510, DateTimeKind.Local).AddTicks(9245),
                            OperationTypeId = 2
                        },
                        new
                        {
                            Id = 25,
                            Amount = 850m,
                            CardId = 2,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 49, 0, 510, DateTimeKind.Local).AddTicks(9248),
                            OperationTypeId = 3
                        },
                        new
                        {
                            Id = 26,
                            Amount = -150m,
                            CardId = 2,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 49, 1, 510, DateTimeKind.Local).AddTicks(9249),
                            OperationTypeId = 2
                        },
                        new
                        {
                            Id = 27,
                            Amount = 0m,
                            CardId = 2,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 49, 2, 510, DateTimeKind.Local).AddTicks(9250),
                            OperationTypeId = 1
                        },
                        new
                        {
                            Id = 28,
                            Amount = 700m,
                            CardId = 2,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 49, 3, 510, DateTimeKind.Local).AddTicks(9252),
                            OperationTypeId = 3
                        },
                        new
                        {
                            Id = 29,
                            Amount = -100m,
                            CardId = 2,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 49, 4, 510, DateTimeKind.Local).AddTicks(9253),
                            OperationTypeId = 2
                        },
                        new
                        {
                            Id = 30,
                            Amount = 0m,
                            CardId = 2,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 49, 5, 510, DateTimeKind.Local).AddTicks(9254),
                            OperationTypeId = 1
                        },
                        new
                        {
                            Id = 31,
                            Amount = 0m,
                            CardId = 3,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 51, 510, DateTimeKind.Local).AddTicks(9255),
                            OperationTypeId = 1
                        },
                        new
                        {
                            Id = 32,
                            Amount = -100m,
                            CardId = 3,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 52, 510, DateTimeKind.Local).AddTicks(9257),
                            OperationTypeId = 2
                        },
                        new
                        {
                            Id = 33,
                            Amount = 1550m,
                            CardId = 3,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 53, 510, DateTimeKind.Local).AddTicks(9258),
                            OperationTypeId = 3
                        },
                        new
                        {
                            Id = 34,
                            Amount = -50m,
                            CardId = 3,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 54, 510, DateTimeKind.Local).AddTicks(9259),
                            OperationTypeId = 2
                        },
                        new
                        {
                            Id = 35,
                            Amount = 0m,
                            CardId = 3,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 55, 510, DateTimeKind.Local).AddTicks(9261),
                            OperationTypeId = 1
                        },
                        new
                        {
                            Id = 36,
                            Amount = 1500m,
                            CardId = 3,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 56, 510, DateTimeKind.Local).AddTicks(9262),
                            OperationTypeId = 3
                        },
                        new
                        {
                            Id = 37,
                            Amount = -300m,
                            CardId = 3,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 57, 510, DateTimeKind.Local).AddTicks(9264),
                            OperationTypeId = 2
                        },
                        new
                        {
                            Id = 38,
                            Amount = 0m,
                            CardId = 3,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 58, 510, DateTimeKind.Local).AddTicks(9265),
                            OperationTypeId = 1
                        },
                        new
                        {
                            Id = 39,
                            Amount = -200m,
                            CardId = 3,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 59, 510, DateTimeKind.Local).AddTicks(9267),
                            OperationTypeId = 2
                        },
                        new
                        {
                            Id = 40,
                            Amount = 1000m,
                            CardId = 3,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 49, 0, 510, DateTimeKind.Local).AddTicks(9268),
                            OperationTypeId = 3
                        },
                        new
                        {
                            Id = 41,
                            Amount = -150m,
                            CardId = 4,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 51, 510, DateTimeKind.Local).AddTicks(9269),
                            OperationTypeId = 2
                        },
                        new
                        {
                            Id = 42,
                            Amount = 0m,
                            CardId = 4,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 52, 510, DateTimeKind.Local).AddTicks(9270),
                            OperationTypeId = 1
                        },
                        new
                        {
                            Id = 43,
                            Amount = 350m,
                            CardId = 4,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 53, 510, DateTimeKind.Local).AddTicks(9271),
                            OperationTypeId = 3
                        },
                        new
                        {
                            Id = 44,
                            Amount = -100m,
                            CardId = 4,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 54, 510, DateTimeKind.Local).AddTicks(9272),
                            OperationTypeId = 2
                        },
                        new
                        {
                            Id = 45,
                            Amount = 0m,
                            CardId = 4,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 55, 510, DateTimeKind.Local).AddTicks(9273),
                            OperationTypeId = 1
                        },
                        new
                        {
                            Id = 46,
                            Amount = 250m,
                            CardId = 4,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 56, 510, DateTimeKind.Local).AddTicks(9275),
                            OperationTypeId = 3
                        },
                        new
                        {
                            Id = 47,
                            Amount = -50m,
                            CardId = 4,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 57, 510, DateTimeKind.Local).AddTicks(9276),
                            OperationTypeId = 2
                        },
                        new
                        {
                            Id = 48,
                            Amount = 0m,
                            CardId = 4,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 58, 510, DateTimeKind.Local).AddTicks(9277),
                            OperationTypeId = 1
                        },
                        new
                        {
                            Id = 49,
                            Amount = 200m,
                            CardId = 4,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 59, 510, DateTimeKind.Local).AddTicks(9279),
                            OperationTypeId = 3
                        },
                        new
                        {
                            Id = 50,
                            Amount = -50m,
                            CardId = 4,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 49, 0, 510, DateTimeKind.Local).AddTicks(9281),
                            OperationTypeId = 2
                        },
                        new
                        {
                            Id = 51,
                            Amount = 0m,
                            CardId = 5,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 51, 510, DateTimeKind.Local).AddTicks(9282),
                            OperationTypeId = 1
                        },
                        new
                        {
                            Id = 52,
                            Amount = -100m,
                            CardId = 5,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 52, 510, DateTimeKind.Local).AddTicks(9283),
                            OperationTypeId = 2
                        },
                        new
                        {
                            Id = 53,
                            Amount = 1050m,
                            CardId = 5,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 53, 510, DateTimeKind.Local).AddTicks(9284),
                            OperationTypeId = 3
                        },
                        new
                        {
                            Id = 54,
                            Amount = -50m,
                            CardId = 5,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 54, 510, DateTimeKind.Local).AddTicks(9285),
                            OperationTypeId = 2
                        },
                        new
                        {
                            Id = 55,
                            Amount = 0m,
                            CardId = 5,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 55, 510, DateTimeKind.Local).AddTicks(9286),
                            OperationTypeId = 1
                        },
                        new
                        {
                            Id = 56,
                            Amount = 1000m,
                            CardId = 5,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 56, 510, DateTimeKind.Local).AddTicks(9288),
                            OperationTypeId = 3
                        },
                        new
                        {
                            Id = 57,
                            Amount = -300m,
                            CardId = 5,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 57, 510, DateTimeKind.Local).AddTicks(9289),
                            OperationTypeId = 2
                        },
                        new
                        {
                            Id = 58,
                            Amount = 0m,
                            CardId = 5,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 58, 510, DateTimeKind.Local).AddTicks(9290),
                            OperationTypeId = 1
                        },
                        new
                        {
                            Id = 59,
                            Amount = 700m,
                            CardId = 5,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 48, 59, 510, DateTimeKind.Local).AddTicks(9291),
                            OperationTypeId = 3
                        },
                        new
                        {
                            Id = 60,
                            Amount = -50m,
                            CardId = 5,
                            OperationDateTime = new DateTime(2024, 5, 13, 22, 49, 0, 510, DateTimeKind.Local).AddTicks(9292),
                            OperationTypeId = 2
                        });
                });

            modelBuilder.Entity("atm.api.domain.OperationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("OperationTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Operación de inicio de sesión de usuario",
                            Name = "Inicio de sesión"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Operación de retiro",
                            Name = "Retiro"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Operación de consulta de saldo",
                            Name = "Saldo"
                        });
                });

            modelBuilder.Entity("atm.api.domain.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("FailedAccessAttempts")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastAccessDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("UserAccounts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardId = 1,
                            FailedAccessAttempts = 0,
                            LastAccessDate = new DateTime(2024, 5, 13, 22, 48, 50, 510, DateTimeKind.Local).AddTicks(9104),
                            Name = "Juan Perez"
                        },
                        new
                        {
                            Id = 2,
                            CardId = 2,
                            FailedAccessAttempts = 0,
                            LastAccessDate = new DateTime(2024, 5, 13, 22, 48, 50, 510, DateTimeKind.Local).AddTicks(9119),
                            Name = "Daniel Smith"
                        },
                        new
                        {
                            Id = 3,
                            CardId = 3,
                            FailedAccessAttempts = 0,
                            LastAccessDate = new DateTime(2024, 5, 13, 22, 48, 50, 510, DateTimeKind.Local).AddTicks(9120),
                            Name = "Alicia Perez"
                        },
                        new
                        {
                            Id = 4,
                            CardId = 4,
                            FailedAccessAttempts = 0,
                            LastAccessDate = new DateTime(2024, 5, 13, 22, 48, 50, 510, DateTimeKind.Local).AddTicks(9121),
                            Name = "Bob Esponja"
                        },
                        new
                        {
                            Id = 5,
                            CardId = 5,
                            FailedAccessAttempts = 0,
                            LastAccessDate = new DateTime(2024, 5, 13, 22, 48, 50, 510, DateTimeKind.Local).AddTicks(9122),
                            Name = "Pepe Argento"
                        });
                });

            modelBuilder.Entity("atm.api.domain.Operation", b =>
                {
                    b.HasOne("atm.api.domain.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("atm.api.domain.OperationType", "OperationType")
                        .WithMany()
                        .HasForeignKey("OperationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("OperationType");
                });

            modelBuilder.Entity("atm.api.domain.UserAccount", b =>
                {
                    b.HasOne("atm.api.domain.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });
#pragma warning restore 612, 618
        }
    }
}
